ldjfdsljflkdsjglkjfdslgkjdsflkgjsfdlkj


ég er maður fólksins

mér finnst gott að borða úldið kjöt en bara með kokteilsósu


ER EITTHVAÐ AÐ ÞV'I?

dsaljkfhasdlkjfhksajdghkfsdlhgkjsdfhgkjsfdhgklfsdh #include kokteilsósu
#include kokteilsósu
lksglkdhgkjhsdkfjghdsfkjghdsfkljghkdsfljhglksdjhglksdfjhglkdsfjhgkldsjfhglkjdsfhglkjdsfhgkljsfdhglkjsdhfgkljsdhflkgjhdsfkljghdsfkljghsdlkfjghfdlksjhgkldsfjhgkldsfjhgsdlkjfhgkldfjh
asdasdasdfasdfsadfasdfsadfsadfsdafasdfasdfsadfdsafsadfsadfasdfasdfasdfsdafasdfsadfsadfasdfsad
FARTFARTAFAERTAFARTFARTSAFARTFARERSADAF