//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLN2_H27.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Data.Entity.Infrastructure;

    public partial class VLN2_2017_H27Entities2 : DbContext
    {
        //public IAppDataContext _db;
        public VLN2_2017_H27Entities2()
            : base("name=VLN2_2017_H27Entities2")
        {
        }

        public VLN2_2017_H27Entities2(IAppDataContext context)
        {
            //_db = context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /*public List<Project> getUserRelatedProjects(string userId)
        {

            var queryResult = (from rel in _db.Project_Users_Relations
                               where rel.UserId == userId
                               join pro in _db.Projects on rel.ProjectId equals pro.Id
                               select pro).ToList();
            return queryResult;
        }*/
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Project_Users_Relations> Project_Users_Relations { get; set; }
    }
}
