//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLN2_H27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int NrOfUsers { get; set; }
        public int NrOfFiles { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
